### ISSUE TITLE
Support traced placeholder for images

### ISSUE THREAD

**Issue by stefanjudis** [contentful-userland/gatsby-contentful-starter#4]
[Traced placeholders](https://github.com/gatsbyjs/gatsby/issues/2435) are a very nice way to improve the user experience for images that are still loading. It would be awesome to have these. 🎉 

![traced](https://user-images.githubusercontent.com/962099/36433725-7ee96ef8-165d-11e8-9292-de6c2e6151a3.gif)

**Comment by axe312ger** [comment]
I love this feature so much and would freak out to see it working with gatsby + contentful.

Issue here is: The tracing has to run on the local machine since contentfuls image api does not support this. We would need to patch the [contentful source plugin](https://www.gatsbyjs.org/packages/gatsby-source-contentful/) to support that feature.

It would have to work somehow this way:
1. Download image from Contentful image API
2. Run the trace from [gatsby-plugin-sharp](https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/#tracedsvg) on these images
3. Extend the query fragments to contain these new traced images as base64

🚀 🎉

**Comment by axe312ger** [comment]
Fixed in #26
