### ISSUE TITLE
Deployment issue related to package.json

### ISSUE THREAD

**Issue by thecodingwhale** [contentful-userland/gatsby-contentful-starter#69]
I was doing some deployment using Netlify and stuck more than 4 hours. I keep scratching my head the build failed issue keep looking this file: `./bin/hello.js` but I can't find it I already run `cleanup-repository` to remove all the setup files.

And then while checking the `package.json` I find this, `"postinstall": "node ./bin/hello.js",`.

It would be better after running the `cleanup-repository` it should delete the `postinstall` and `cleanup-repository` in `package.json`

Also how I can create PR for this? Thank you.

**Comment by stefanjudis** [comment]
@thecodingwhale That is very valid and I agree that the cleanup should also adjust the `package.json` to remove the `post-install` and `cleanup-repository` script. 

I'm happy to take a PR that adjusts the package.json. If you need help with "how to make a PR" I'm happy to guide you to the right resources. :)

**Comment by thecodingwhale** [comment]
hi @stefanjudis I would happily create a PR for this one :) Can you help me how? Thank you.

**Comment by stefanjudis** [comment]
Because you don't have write access to this repo you'd have to create a fork to your user account. :) `gatsby-contentful-starter` will then be available in your own github account.

Then you can add the changes you want to perform. In this case, you could add another script, that reads the package.json and removes the unneeded scripts. (there are other ways to do that but this is how I would approach it 🙈) This script would then need to be deleted in the clean up too. :) 

After you committed and pushed your changes to your fork, you can follow [the GitHub instructions to open a pull request](https://help.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to the original userland repository. :) 

Does that help?

**Comment by thecodingwhale** [comment]
hi @stefanjudis I've created a PR for the fix for this one:
https://github.com/contentful-userland/gatsby-contentful-starter/pull/73

thank you.

**Comment by stefanjudis** [comment]
Looking at it already. :) I'll have some tiny notes for improvement, but looks good. :) 

Thank you!

**Comment by thecodingwhale** [comment]
@stefanjudis if you have new ideas to improve this project. Just ask me and I'm willing to help you out :)

**Comment by stefanjudis** [comment]
There are some open issues, that could be tackled. And just FYI, we one merged PR you get write access to the repo/org. :) 

As long as you follow PRs (feel free to tag me too) you can move forward with things you consider to be valuable to the community. :) 

THanks again!
